version: "3.8"

services:
  mongodb:
    container_name: database
    image: mongo:5.0.3
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27018:27017
    networks:
      - application

    app:
    container_name: goapp
    restart: always
    build: .
    ports:
      - 8080:8000
    networks:
      - application
    links:
      - mongodb
    depends_on:
      - mongodb
    
networks:
  application:
    driver: bridge